/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PerfectMLStandaloneSetup extends PerfectMLStandaloneSetupGenerated {

	public static void doSetup() {
		new PerfectMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
