/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML.perfectML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getAlgorithm()
 * @model
 * @generated
 */
public interface Algorithm extends EObject
{
} // Algorithm
