/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML.perfectML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Declarations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#getTarget <em>Target</em>}</li>
 *   <li>{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#isTarget_def <em>Target def</em>}</li>
 *   <li>{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#getPredictive <em>Predictive</em>}</li>
 *   <li>{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#isPred_def <em>Pred def</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getColumnDeclarations()
 * @model
 * @generated
 */
public interface ColumnDeclarations extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(ColumnSet)
   * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getColumnDeclarations_Target()
   * @model containment="true"
   * @generated
   */
  ColumnSet getTarget();

  /**
   * Sets the value of the '{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(ColumnSet value);

  /**
   * Returns the value of the '<em><b>Target def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target def</em>' attribute.
   * @see #setTarget_def(boolean)
   * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getColumnDeclarations_Target_def()
   * @model
   * @generated
   */
  boolean isTarget_def();

  /**
   * Sets the value of the '{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#isTarget_def <em>Target def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target def</em>' attribute.
   * @see #isTarget_def()
   * @generated
   */
  void setTarget_def(boolean value);

  /**
   * Returns the value of the '<em><b>Predictive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predictive</em>' containment reference.
   * @see #setPredictive(ColumnSet)
   * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getColumnDeclarations_Predictive()
   * @model containment="true"
   * @generated
   */
  ColumnSet getPredictive();

  /**
   * Sets the value of the '{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#getPredictive <em>Predictive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predictive</em>' containment reference.
   * @see #getPredictive()
   * @generated
   */
  void setPredictive(ColumnSet value);

  /**
   * Returns the value of the '<em><b>Pred def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred def</em>' attribute.
   * @see #setPred_def(boolean)
   * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getColumnDeclarations_Pred_def()
   * @model
   * @generated
   */
  boolean isPred_def();

  /**
   * Sets the value of the '{@link org.xtext.example.perfectML.perfectML.ColumnDeclarations#isPred_def <em>Pred def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pred def</em>' attribute.
   * @see #isPred_def()
   * @generated
   */
  void setPred_def(boolean value);

} // ColumnDeclarations
