/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML.perfectML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.perfectML.perfectML.Output#getPATH <em>PATH</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getOutput()
 * @model
 * @generated
 */
public interface Output extends EObject
{
  /**
   * Returns the value of the '<em><b>PATH</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PATH</em>' attribute.
   * @see #setPATH(String)
   * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getOutput_PATH()
   * @model
   * @generated
   */
  String getPATH();

  /**
   * Sets the value of the '{@link org.xtext.example.perfectML.perfectML.Output#getPATH <em>PATH</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PATH</em>' attribute.
   * @see #getPATH()
   * @generated
   */
  void setPATH(String value);

} // Output
