/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML.perfectML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.perfectML.perfectML.PerfectMLFile#getPrograms <em>Programs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getPerfectMLFile()
 * @model
 * @generated
 */
public interface PerfectMLFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Programs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.perfectML.perfectML.Program}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Programs</em>' containment reference list.
   * @see org.xtext.example.perfectML.perfectML.PerfectMLPackage#getPerfectMLFile_Programs()
   * @model containment="true"
   * @generated
   */
  EList<Program> getPrograms();

} // PerfectMLFile
