/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PerfectMLUiModule extends AbstractPerfectMLUiModule {

	public PerfectMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
