/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.File#getPATH <em>PATH</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFile()
 * @model
 * @generated
 */
public interface File extends EObject
{
  /**
   * Returns the value of the '<em><b>PATH</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PATH</em>' attribute.
   * @see #setPATH(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFile_PATH()
   * @model
   * @generated
   */
  String getPATH();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.File#getPATH <em>PATH</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PATH</em>' attribute.
   * @see #getPATH()
   * @generated
   */
  void setPATH(String value);

} // File
