/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FLOAT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FLOAT#getIntPart <em>Int Part</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FLOAT#getDecPart <em>Dec Part</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFLOAT()
 * @model
 * @generated
 */
public interface FLOAT extends EObject
{
  /**
   * Returns the value of the '<em><b>Int Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Part</em>' attribute.
   * @see #setIntPart(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFLOAT_IntPart()
   * @model
   * @generated
   */
  int getIntPart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FLOAT#getIntPart <em>Int Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Part</em>' attribute.
   * @see #getIntPart()
   * @generated
   */
  void setIntPart(int value);

  /**
   * Returns the value of the '<em><b>Dec Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec Part</em>' attribute.
   * @see #setDecPart(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFLOAT_DecPart()
   * @model
   * @generated
   */
  int getDecPart();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FLOAT#getDecPart <em>Dec Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec Part</em>' attribute.
   * @see #getDecPart()
   * @generated
   */
  void setDecPart(int value);

} // FLOAT
