/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ParameterDeclaration#getBloc <em>Bloc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParameterDeclaration()
 * @model
 * @generated
 */
public interface ParameterDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Bloc</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ParaDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bloc</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParameterDeclaration_Bloc()
   * @model containment="true"
   * @generated
   */
  EList<ParaDeclaration> getBloc();

} // ParameterDeclaration
