/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Value#getInt <em>Int</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Value#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Value#getFloat <em>Float</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Value#getBool <em>Bool</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getValue_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Value#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getValue_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Value#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

  /**
   * Returns the value of the '<em><b>Float</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float</em>' containment reference.
   * @see #setFloat(FLOAT)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getValue_Float()
   * @model containment="true"
   * @generated
   */
  FLOAT getFloat();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Value#getFloat <em>Float</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float</em>' containment reference.
   * @see #getFloat()
   * @generated
   */
  void setFloat(FLOAT value);

  /**
   * Returns the value of the '<em><b>Bool</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' containment reference.
   * @see #setBool(BOOL)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getValue_Bool()
   * @model containment="true"
   * @generated
   */
  BOOL getBool();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Value#getBool <em>Bool</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' containment reference.
   * @see #getBool()
   * @generated
   */
  void setBool(BOOL value);

} // Value
