/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.perfectML.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.perfectML.PerfectMLRuntimeModule;
import org.xtext.example.perfectML.PerfectMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PerfectMLIdeSetup extends PerfectMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PerfectMLRuntimeModule(), new PerfectMLIdeModule()));
	}
	
}
